-- Demo tournament seed — generated, safe to re-run.
DELETE FROM fm_tournament_entries WHERE user_id IN (SELECT id FROM fm_users WHERE google_sub LIKE 'demo-%');
DELETE FROM fm_tournament_participants WHERE user_id IN (SELECT id FROM fm_users WHERE google_sub LIKE 'demo-%');
DELETE FROM fm_tournaments WHERE name = 'Demo Derby — Walleye Shootout';
DELETE FROM fm_users WHERE google_sub LIKE 'demo-%';

INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-1', 'Gordie Sawchuk');
INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-2', 'Marcy Desjarlais');
INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-3', 'Big Jim Kozak');
INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-4', 'Tammy Roulette');
INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-5', 'Daryl Peters');
INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-6', 'Shania Courchene');
INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-7', 'Ole Bjornson');
INSERT INTO fm_users (google_sub, name) VALUES ('demo-angler-8', 'Kevin Traverse');

INSERT INTO fm_tournaments
  (name, description, organizer_id, lake_ids, species, starts_at, ends_at, rules, scoring, invite_code, status)
VALUES (
  'Demo Derby — Walleye Shootout',
  'Demo tournament to verify the leaderboard display. Not a real event.',
  (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-1'),
  ARRAY['lake-winnipeg'],
  ARRAY['Walleye'],
  now() - interval '2 days',
  now() + interval '5 days',
  'Demo rules: longest walleye wins. All entries auto-approved for the demo.',
  'longest',
  'DEMO12',
  'active'
);

INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-1'));
INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-2'));
INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-3'));
INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-4'));
INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-5'));
INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-6'));
INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-7'));
INSERT INTO fm_tournament_participants (tournament_id, user_id) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-8'));

INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-1'), 'https://images.unsplash.com/photo-1609859682240-6860cf3d99d5?auto=format&fit=crop&w=800&q=60', 'Walleye', 24.0, 50.4618, -97.11, 12, 'Demo catch', 'approved', now() - interval '19 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-1'), 'https://images.unsplash.com/photo-1516684732162-798a006aa609?auto=format&fit=crop&w=800&q=60', 'Walleye', 21.5, 50.3435, -97.0642, 12, 'Demo catch', 'approved', now() - interval '8 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-1'), 'https://images.unsplash.com/photo-1499242611767-cf8b9be02854?auto=format&fit=crop&w=800&q=60', 'Walleye', 19.0, 50.473, -96.7631, 12, 'Demo catch', 'approved', now() - interval '7 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-2'), 'https://images.unsplash.com/photo-1516684732162-798a006aa609?auto=format&fit=crop&w=800&q=60', 'Walleye', 22.5, 50.4471, -97.1073, 12, 'Demo catch', 'approved', now() - interval '7 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-2'), 'https://images.unsplash.com/photo-1499242611767-cf8b9be02854?auto=format&fit=crop&w=800&q=60', 'Walleye', 20.0, 50.3356, -96.9179, 12, 'Demo catch', 'approved', now() - interval '3 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-3'), 'https://images.unsplash.com/photo-1499242611767-cf8b9be02854?auto=format&fit=crop&w=800&q=60', 'Walleye', 28.5, 50.4384, -96.8336, 12, 'Demo catch', 'approved', now() - interval '36 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-3'), 'https://images.unsplash.com/photo-1541742425281-c1d3fc8aff96?auto=format&fit=crop&w=800&q=60', 'Walleye', 25.0, 50.3959, -96.9403, 12, 'Demo catch', 'approved', now() - interval '19 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-3'), 'https://images.unsplash.com/photo-1609859682240-6860cf3d99d5?auto=format&fit=crop&w=800&q=60', 'Walleye', 23.5, 50.5128, -97.1174, 12, 'Demo catch', 'approved', now() - interval '12 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-3'), 'https://images.unsplash.com/photo-1516684732162-798a006aa609?auto=format&fit=crop&w=800&q=60', 'Walleye', 21.0, 50.4794, -96.9839, 12, 'Demo catch', 'approved', now() - interval '11 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-4'), 'https://images.unsplash.com/photo-1541742425281-c1d3fc8aff96?auto=format&fit=crop&w=800&q=60', 'Walleye', 19.5, 50.3346, -96.8146, 12, 'Demo catch', 'approved', now() - interval '8 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-4'), 'https://images.unsplash.com/photo-1609859682240-6860cf3d99d5?auto=format&fit=crop&w=800&q=60', 'Walleye', 18.0, 50.2978, -97.0813, 12, 'Demo catch', 'approved', now() - interval '24 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-5'), 'https://images.unsplash.com/photo-1609859682240-6860cf3d99d5?auto=format&fit=crop&w=800&q=60', 'Walleye', 26.0, 50.4511, -96.7971, 12, 'Demo catch', 'approved', now() - interval '31 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-5'), 'https://images.unsplash.com/photo-1516684732162-798a006aa609?auto=format&fit=crop&w=800&q=60', 'Walleye', 24.5, 50.4309, -96.7308, 12, 'Demo catch', 'approved', now() - interval '26 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-6'), 'https://images.unsplash.com/photo-1516684732162-798a006aa609?auto=format&fit=crop&w=800&q=60', 'Walleye', 21.0, 50.2936, -97.0027, 12, 'Demo catch', 'approved', now() - interval '25 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-6'), 'https://images.unsplash.com/photo-1499242611767-cf8b9be02854?auto=format&fit=crop&w=800&q=60', 'Walleye', 20.5, 50.4432, -96.8382, 12, 'Demo catch', 'approved', now() - interval '4 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-6'), 'https://images.unsplash.com/photo-1541742425281-c1d3fc8aff96?auto=format&fit=crop&w=800&q=60', 'Walleye', 19.75, 50.4684, -96.8108, 12, 'Demo catch', 'approved', now() - interval '7 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-7'), 'https://images.unsplash.com/photo-1499242611767-cf8b9be02854?auto=format&fit=crop&w=800&q=60', 'Walleye', 23.0, 50.5266, -96.7734, 12, 'Demo catch', 'approved', now() - interval '26 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-8'), 'https://images.unsplash.com/photo-1541742425281-c1d3fc8aff96?auto=format&fit=crop&w=800&q=60', 'Walleye', 25.5, 50.3534, -96.8657, 12, 'Demo catch', 'approved', now() - interval '25 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-8'), 'https://images.unsplash.com/photo-1609859682240-6860cf3d99d5?auto=format&fit=crop&w=800&q=60', 'Walleye', 22.0, 50.3188, -96.9779, 12, 'Demo catch', 'approved', now() - interval '19 hours');
INSERT INTO fm_tournament_entries (tournament_id, user_id, photo_url, species, length_inches, latitude, longitude, gps_accuracy, notes, status, captured_at) VALUES ((SELECT id FROM fm_tournaments WHERE invite_code = 'DEMO12'), (SELECT id FROM fm_users WHERE google_sub = 'demo-angler-8'), 'https://images.unsplash.com/photo-1516684732162-798a006aa609?auto=format&fit=crop&w=800&q=60', 'Walleye', 20.25, 50.4805, -96.8466, 12, 'Demo catch', 'approved', now() - interval '6 hours');
