/** Client-safe FishMB constants (no node imports). */

export const LAKE_REGIONS = [
  "Eastern",
  "Interlake",
  "Northern",
  "Parkland",
  "Southern",
  "Western",
] as const;

/**
 * Real photos researched per lake (Wikimedia Commons, Manitoba-verified) and
 * per lodge (the lodge's own website og:image). Generated by
 * scripts/fetch-real-photos.py — entries are {id: {url, title?}} or {id: {url}}.
 */
import realPhotos from "./fishmb-photos.json";

type PhotoMap = Record<string, { url: string; title?: string; credit?: string; license?: string }>;

function realPhotoUrl(kind: "lakes" | "lodges", id: string): string | null {
  const entry = (realPhotos as { lakes: PhotoMap; lodges: PhotoMap })[kind]?.[id];
  return entry?.url ?? null;
}

/**
 * Verified lake/fishing photos (each one visually checked — no stock-photo
 * roulette). Used as a fallback when no real photo of the specific lake was
 * found; the lake records' picsum URLs resolve to unrelated subjects.
 */
const LAKE_PHOTO_IDS = [
  "1439066615861-d1af74d74000", // wooden dock on a pine lake
  "1501785888041-af3ef285b470", // turquoise lake with boats
  "1476514525535-07fb3b4ae5f1", // wooden boat bow on a lake
  "1541742425281-c1d3fc8aff96", // fishing rods at sunset over water
  "1609859682240-6860cf3d99d5", // anglers fishing a green lake
] as const;

export function lakePhotoUrl(id: string, w = 800): string {
  const real = realPhotoUrl("lakes", id);
  if (real) return real;
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  const photo = LAKE_PHOTO_IDS[h % LAKE_PHOTO_IDS.length];
  return `https://images.unsplash.com/photo-${photo}?auto=format&fit=crop&w=${w}&q=60`;
}

/** True when we have a researched real photo of this lake. */
export function hasRealLakePhoto(id: string): boolean {
  return realPhotoUrl("lakes", id) !== null;
}

/** Attribution for a real lake photo (Wikimedia Commons), or null. */
export function lakePhotoCredit(id: string): string | null {
  const entry = (realPhotos as { lakes: PhotoMap; lodges: PhotoMap }).lakes?.[id];
  if (!entry?.credit) return "Photo: Wikimedia Commons contributors";
  const lic = entry.license ? ` (${entry.license})` : "";
  return `Photo: ${entry.credit}${lic} via Wikimedia Commons`;
}

/** Real lodge photo (from the lodge's own site), or null. */
export function lodgePhotoUrl(id: string): string | null {
  return realPhotoUrl("lodges", id);
}

export interface HeroPhoto {
  src: string;
  alt: string;
  credit: string;
}

/**
 * Rotating hero photos — real Manitoba lakes, researched on Wikimedia
 * Commons (freely licensed; credit shown on the hero). Thumbnail URLs at
 * 1920px wide, each verified 200 + image/jpeg.
 */
export const FISHMB_HERO_PHOTOS: HeroPhoto[] = [
  {
    src: "https://commons.wikimedia.org/wiki/Special:FilePath/Riding%20Mountain%20National%20Park%2C%20Wasagaming%2C%20Clear%20Lake%20%28340309%29%20%2813491133804%29.jpg?width=1920",
    alt: "Clear Lake in Riding Mountain National Park",
    credit: "Robert Linsdell, CC BY 2.0",
  },
  {
    src: "https://commons.wikimedia.org/wiki/Special:FilePath/Fishing%20in%20a%20Sunset%20in%20Matlock%2C%20Manitoba%2C%20Canada.jpg?width=1920",
    alt: "Fishing at sunset in Matlock, Manitoba",
    credit: "Will Darracott, CC BY-SA 4.0",
  },
  {
    src: "https://commons.wikimedia.org/wiki/Special:FilePath/Lake%20Manitoba%20comin%27%20at%20ya%20near%20Steep%20Rock%2C%20Manitoba%2C%20Canada.%20%2836378663843%29.jpg?width=1920",
    alt: "Lake Manitoba shoreline near Steep Rock",
    credit: "Rob Swystun, CC BY 2.0",
  },
  {
    src: "https://commons.wikimedia.org/wiki/Special:FilePath/Falcon%20Lake%20Manitoba%20Canada%20Summer%202009.JPG?width=1920",
    alt: "Falcon Lake in summer, Whiteshell",
    credit: "Shahnoor Habib Munmun, CC BY 3.0",
  },
  {
    src: "https://commons.wikimedia.org/wiki/Special:FilePath/Clearwater%20lake.jpg?width=1920",
    alt: "Sunset over Clearwater Lake from the docks",
    credit: "Canbun, CC BY-SA 4.0",
  },
];

/** Kept for backward compatibility — the first rotating hero photo. */
export const FISHMB_HERO_PHOTO = FISHMB_HERO_PHOTOS[0].src;

export const FISHMB_CTA_PHOTO =
  "https://images.unsplash.com/photo-1541742425281-c1d3fc8aff96?auto=format&fit=crop&w=1800&q=70";

/**
 * Public Google OAuth web client ID (same one the FishMB app uses).
 * Client IDs are public by design — they ship in client-side code.
 * The website exchanges the GIS ID token at POST /api/fish/auth/google,
 * which verifies it and creates a session in the same fm_users database.
 */
export const FISHMB_GOOGLE_CLIENT_ID =
  process.env.NEXT_PUBLIC_FISHMB_GOOGLE_CLIENT_ID ||
  "544282207513-u3ncjmbht90lksed0m81hprf1d1at42t.apps.googleusercontent.com";

export const FISHMB_TOKEN_KEY = "fishmb_token";
